shop/Controllers/FavoritesController.cs
using Data.Entities;
using Data;
using Microsoft.AspNetCore.Mvc;
using shop.Helpers;

namespace shop.Controllers
{
    public class FavoritesController : Controller
    {
        const string Key = "Items";
        private readonly shopdbcontext context;

        public FavoritesController(shopdbcontext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var ids = HttpContext.Session.Get<List<int>>(Key);
            ids ??= new List<int>();

            List<Product?> products = ids.Select(id => context.products.Find(id)).ToList();

            return View(products);
        }

        public IActionResult Add(int id)
        {
            List<int>? ids = HttpContext.Session.Get<List<int>>(Key);

            ids ??= new List<int>();

            ids.Add(id);

            HttpContext.Session.Set(Key, ids);

            return RedirectToAction("Products", "Product");
        }

        public IActionResult Remove(int id)
        {
            List<int>? ids = HttpContext.Session.Get<List<int>>(Key);

            ids ??= new List<int>();

            ids.Remove(id);

            HttpContext.Session.Set(Key, ids);

            return RedirectToAction("Index");
        }
    }
}

shop/Views/Favorites/Index.cshtml
@model List<Data.Entities.Product>;
<div class="row">

    @foreach (var p in Model)
    {
        <div class="card col col-3" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@p.Name</h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">@p.Price$</h6>
                <p class="card-text pb-3">@p.description</p>
                <div class="container position-absolute fixed-bottom">
                    <a asp-action="Details" asp-route-id="@p.Id" class=" btn btn-primary">Details</a>
                    <a asp-controller="Favorites" asp-action="Remove" asp-route-id="@p.Id" class=" btn btn-danger">♥</a>

                </div>
            </div>
        </div>
    }
</div>